name: Build Common Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore NuGet packages
        run: dotnet restore Common/Common.csproj

      - name: Build Common Project
        run: dotnet build Common/Common.csproj
